# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: STOR-601 Introductory Python
author: Daniel Grose
logo: data_structures_1024x576.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex


